In [6]:
import tensorflow as tf

const_a = tf.constant([1,2,3,4], shape=[2,2], dtype=tf.float32)

# print("value of the constant const_a:", const_a.numpy())
# print("data type of the constant const_a:", const_a.dtype)
# print("shape of the constant const_a:", const_a.shape)
# print("name of the device that is to generate the constant const_a:", const_a.device)

zeros_b = tf.zeros(shape=[2, 3], dtype=tf.int32)

zeros_like_c = tf.zeros_like(const_a)
# print(zeros_like_c.numpy())

fill_d = tf.fill([3, 3], 8)
# print(fill_d.numpy())

random_e = tf.random.normal([5, 5], mean=0, stddev=1.0, seed=1)
# print(random_e.numpy())

list_f = [1, 2, 3, 4, 5, 6]
type(list_f)


list

In [7]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [8]:
var_1 = tf.Variable(tf.ones([2, 3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
print("Value of the variable var_1:", var_1.read_value())
# Assign a variable value

Value of the variable var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
var_value_1 = [[1, 2, 3], [4, 5, 6]]
var_1.assign(var_value_1)
print("Value of the variable var_1 after the assignment:", var_1.read_value())

Value of the variable var_1 after the assignment: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [11]:
# Variable addition
var_1.assign_add(tf.ones([2, 3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [12]:
tensor_h = tf.random.normal([4, 100, 100, 3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.708499  , -0.69881064, -0.08849752],
         [-0.0283459 ,  0.7866868 ,  0.8754089 ],
         [-0.29807848,  0.46198174,  0.6425823 ],
         ...,
         [-0.14799447,  1.9119095 ,  0.22121094],
         [ 0.9289796 , -1.1730258 ,  0.42780662],
         [ 2.0093286 , -0.7940872 , -2.6945283 ]],

        [[ 0.01198264,  0.3444871 ,  0.5620876 ],
         [ 0.06845685,  0.04275658, -1.1321461 ],
         [-1.0250046 , -0.2749105 , -0.21277174],
         ...,
         [-0.50398695, -0.10934751, -2.5185058 ],
         [ 0.46655822,  1.2563702 ,  0.7102396 ],
         [-0.24981901,  0.80425435, -1.0292767 ]],

        [[-0.4329081 , -1.03243   , -0.07005912],
         [-0.45088083,  1.9017277 , -1.2767045 ],
         [-1.5801755 ,  0.8755078 ,  0.84709257],
         ...,
         [-1.3289641 ,  0.15220729,  0.6485158 ],
         [ 0.21742114,  0.08957648, -0.03406593],
         [ 0.9851339 ,  0.2081858 ,  1.0077838

In [13]:
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-0.708499  , -0.69881064, -0.08849752],
        [-0.0283459 ,  0.7866868 ,  0.8754089 ],
        [-0.29807848,  0.46198174,  0.6425823 ],
        ...,
        [-0.14799447,  1.9119095 ,  0.22121094],
        [ 0.9289796 , -1.1730258 ,  0.42780662],
        [ 2.0093286 , -0.7940872 , -2.6945283 ]],

       [[ 0.01198264,  0.3444871 ,  0.5620876 ],
        [ 0.06845685,  0.04275658, -1.1321461 ],
        [-1.0250046 , -0.2749105 , -0.21277174],
        ...,
        [-0.50398695, -0.10934751, -2.5185058 ],
        [ 0.46655822,  1.2563702 ,  0.7102396 ],
        [-0.24981901,  0.80425435, -1.0292767 ]],

       [[-0.4329081 , -1.03243   , -0.07005912],
        [-0.45088083,  1.9017277 , -1.2767045 ],
        [-1.5801755 ,  0.8755078 ,  0.84709257],
        ...,
        [-1.3289641 ,  0.15220729,  0.6485158 ],
        [ 0.21742114,  0.08957648, -0.03406593],
        [ 0.9851339 ,  0.2081858 ,  1.0077838 ]],

       ...,

     

In [14]:
tensor_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.708499  , -0.69881064, -0.08849752],
         [-0.0283459 ,  0.7866868 ,  0.8754089 ],
         [-0.29807848,  0.46198174,  0.6425823 ],
         ...,
         [-0.14799447,  1.9119095 ,  0.22121094],
         [ 0.9289796 , -1.1730258 ,  0.42780662],
         [ 2.0093286 , -0.7940872 , -2.6945283 ]],

        [[ 0.01198264,  0.3444871 ,  0.5620876 ],
         [ 0.06845685,  0.04275658, -1.1321461 ],
         [-1.0250046 , -0.2749105 , -0.21277174],
         ...,
         [-0.50398695, -0.10934751, -2.5185058 ],
         [ 0.46655822,  1.2563702 ,  0.7102396 ],
         [-0.24981901,  0.80425435, -1.0292767 ]],

        [[-0.4329081 , -1.03243   , -0.07005912],
         [-0.45088083,  1.9017277 , -1.2767045 ],
         [-1.5801755 ,  0.8755078 ,  0.84709257],
         ...,
         [-1.3289641 ,  0.15220729,  0.6485158 ],
         [ 0.21742114,  0.08957648, -0.03406593],
         [ 0.9851339 ,  0.2081858 ,  1.0077838

In [15]:
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.5024486 , -0.6001964 , -1.3551089 ],
         [ 0.6945798 , -0.2125598 ,  0.28777918],
         [ 1.4433903 , -1.1192378 , -2.0349312 ],
         ...,
         [-2.0399275 , -2.7469442 ,  0.2426562 ],
         [ 0.5811279 ,  0.3892726 , -0.6812132 ],
         [-1.2367331 , -0.02258345,  0.62265414]],

        [[-0.28528333, -0.37852088, -1.0388224 ],
         [ 0.5551271 ,  1.858153  ,  0.9006755 ],
         [-0.22109576, -0.01086124,  2.0961256 ],
         ...,
         [ 0.24956517,  0.96746093, -1.3508455 ],
         [ 0.0871203 , -0.7468594 ,  0.8911886 ],
         [ 0.8036201 , -1.3905193 , -1.4801078 ]],

        [[ 0.6927035 , -0.47141048, -0.16485149],
         [ 0.3010119 , -0.43023986,  1.1416911 ],
         [ 0.88560057,  0.35115564, -0.98072505],
         ...,
         [-1.5053203 , -0.15968171,  0.309447  ],
         [-0.2663097 , -0.650797  ,  0.783981  ],
         [-0.04772759,  0.13511886, -0.1531006

In [16]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.5800464>

In [17]:
#Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).

In [18]:
indices = [0, 1, 3]
tf.gather(tensor_h, axis=0, indices=indices)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.708499  , -0.69881064, -0.08849752],
         [-0.0283459 ,  0.7866868 ,  0.8754089 ],
         [-0.29807848,  0.46198174,  0.6425823 ],
         ...,
         [-0.14799447,  1.9119095 ,  0.22121094],
         [ 0.9289796 , -1.1730258 ,  0.42780662],
         [ 2.0093286 , -0.7940872 , -2.6945283 ]],

        [[ 0.01198264,  0.3444871 ,  0.5620876 ],
         [ 0.06845685,  0.04275658, -1.1321461 ],
         [-1.0250046 , -0.2749105 , -0.21277174],
         ...,
         [-0.50398695, -0.10934751, -2.5185058 ],
         [ 0.46655822,  1.2563702 ,  0.7102396 ],
         [-0.24981901,  0.80425435, -1.0292767 ]],

        [[-0.4329081 , -1.03243   , -0.07005912],
         [-0.45088083,  1.9017277 , -1.2767045 ],
         [-1.5801755 ,  0.8755078 ,  0.84709257],
         ...,
         [-1.3289641 ,  0.15220729,  0.6485158 ],
         [ 0.21742114,  0.08957648, -0.03406593],
         [ 0.9851339 ,  0.2081858 ,  1.0077838

In [19]:
#Extract the pixel in [1,1] from the first dimension of the first image and the pixel in [2,2] from the first dimension of the second image in tensot_h ([4,100,100,3]).
indices = [[0, 1, 1, 0], [1, 2, 2, 0]]
tf.gather_nd(tensor_h, indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.06845685, 2.3097613 ], dtype=float32)>

In [20]:
const_d_1 = tf.constant([[1, 2, 3, 4]], shape=[2,2], dtype=tf.float32)
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [21]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [22]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:",expand_sample_1.shape)
print("add a dimension before the first dimension (axis = 0): ",tf.expand_dims(expand_sample_1,
axis=0).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1,
axis=1).shape)
print("add a dimension after the last dimension (axis = –1): ",tf.expand_dims(expand_sample_1,
axis=-1).shape)

size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)
add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)


In [23]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print("size of the original data:",squeeze_sample_1.shape)
squeezed_sample_1 = tf.squeeze(expand_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

size of the original data: (1, 100, 100, 3)
data size after dimension squeezing: (100, 100, 3)


In [24]:
#Input the tensor to be transposed, and call tf.transpose.
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("size of the original data:",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:",transposed_sample_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


In [25]:
#Generate an $ x 100 x 200 x 3 tensor to represent four 100 x 200 three-channel color images.
trans_sample_2 = tf.random.normal([4,100,200,3])
print("size of the original data:",trans_sample_2.shape)
#Exchange the length and width for the four images: The original perm value is [0,1,2,3], and the new perm value is [0,2,1,3].
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,1,3])
print("size of transposed data:",transposed_sample_2.shape)

size of the original data: (4, 100, 200, 3)
size of transposed data: (4, 200, 100, 3)


In [26]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcasted data:",broadcasted_sample_1.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [27]:
#During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[ 0, 0, 0],
[10,10,10],
[20,20,20],
[30,30,30]])
b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [28]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [29]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

In [30]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor:",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column:",max_sample_1.numpy())
print("locate the maximum value by row:",max_sample_2.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
locate the maximum value by column: [2 1 2]
locate the maximum value by row: [1 2 2]


In [31]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())
print("calculate the sum of all elements in the tensor (axis = None):",tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("calculate the sum of elements in each column by column (axis = 0):",tf.reduce_sum(reduce_sample_1,axis=0).numpy())
print("calculate the sum of elements in each column by row (axis = 1):",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

original data [[1 2 3]
 [4 5 6]]
calculate the sum of all elements in the tensor (axis = None): 21
calculate the sum of elements in each column by column (axis = 0): [5 7 9]
calculate the sum of elements in each column by row (axis = 1): [ 6 15]


In [32]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)
size of the concatenated data: (44, 100, 100, 3)


In [34]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)


In [35]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 0.7533009 ,  0.7866439 , -0.6011081 ],
         [-0.40843448, -0.7839384 ,  0.62703156],
         [-0.76226234, -0.46797058,  1.3294857 ],
         ...,
         [-0.21432458, -0.6667148 ,  0.05725569],
         [ 0.5804937 , -0.3714992 ,  0.5055186 ],
         [ 1.858014  ,  0.4569773 , -0.80055064]],
 
        [[-0.6828436 , -1.1681211 ,  0.00948644],
         [-0.26807758, -1.3218242 ,  0.2330245 ],
         [-2.007303  ,  0.45696288, -0.65567243],
         ...,
         [ 0.70009804,  0.58101195,  0.42246854],
         [ 0.00619851, -1.8929034 , -1.1935722 ],
         [ 0.90043026, -0.03827969, -0.17394018]],
 
        [[-0.12830527,  0.1667647 ,  0.6780556 ],
         [-1.5887357 ,  2.5334508 , -1.1587029 ],
         [ 0.5321883 ,  0.2864255 , -1.5541363 ],
         ...,
         [ 0.4538675 ,  2.7107294 , -0.49791363],
         [-1.1716158 , -0.03177375, -1.6398343 ],
         [-1.1187683 ,  0.0241212 ,  1.1859847

In [38]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",np.shape(splited_sample_2[0]),np.shape(splited_sample_2[1]),np.shape(splited_sample_2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [39]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

input tensor: [4 3 9 6 8 2 0 5 7 1]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements in ascending order: [6 9 5 1 0 7 3 8 4 2]


In [40]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())
print("first five values in ascending order:", values.numpy())
print("indexes of the first five values in ascending order:", index.numpy())

input tensor: [4 3 9 6 8 2 0 5 7 1]
first five values in ascending order: [9 8 7 6 5]
indexes of the first five values in ascending order: [2 4 8 3 7]


In [41]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2],
[3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [42]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2],
[3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
#Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [1]:
import tensorflow as tf
thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)
if thre_1.numpy() > 0.5:
    y = tf.matmul(x, x)
else:
    y = tf.add(x, x)

tf.Tensor(0.53932333, shape=(), dtype=float32)


In [2]:
@tf.function
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x)+b)
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.74815965, 1.3353727 , 1.0057325 ],
       [0.81977856, 1.4063201 , 1.2111651 ],
       [1.1486473 , 2.2426376 , 1.8771436 ]], dtype=float32)>

In [4]:
#Use the timeit module to measure the execution time of a small code segment.
import timeit
#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))
#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
    return CNN_cell(image)
image = tf.zeros([100, 200, 200, 3])
#Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)
#Call timeit.timeit to measure the time required for executing the code 10 times.
print("time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("time required for performing the computation of one CNN layer in graph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))

time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode: 7.177175699995132
time required for performing the computation of one CNN layer in graph mode: 4.035388300006161


In [5]:
import tensorflow.keras.layers as layers

In [6]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [7]:
#Use the output of the previous layer as the input of the next layer.
x = tf.keras.Input(shape=(32,))
h1 = layers.Dense(32, activation='relu')(x)
h2 = layers.Dense(32, activation='relu')(h1)
y = layers.Dense(10, activation='softmax')(h2)
model_sample_2 = tf.keras.models.Model(x, y)
#Print model information.
model_sample_2.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dense_5 (Dense)             (None, 10)                330       
                                                                 
Total params: 2442 (9.54 KB)
Trainable params: 2442 (9.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
#Create a fully connected layer that contains 32 neurons. Set the activation function to sigmoid.
#The activation parameter can be set to a function name string, for example, sigmoid or a function object, for example, tf.sigmoid.
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
#Set kernel_initializer.
layers.Dense(32, kernel_initializer=tf.keras.initializers.he_normal)
#Set kernel_regularizer to L2 regularization.
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))

In [10]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

In [12]:
layers.MaxPool2D(pool_size=(2,2),strides=(2,1))

In [13]:
import numpy as np
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
#Sequences t1, t2, and t3
data = [[[0.1],
[0.2],
[0.3]]]
print(data)
print("output when return_sequences is set to True",model_lstm_1.predict(data))
print("output when return_sequences is set to False",model_lstm_2.predict(data))

[[[0.1], [0.2], [0.3]]]
1/1 [==============================] - 0s 357ms/step
output when return_sequences is set to True [[[0.0075277 ]
  [0.01956571]
  [0.03395714]]]
1/1 [==============================] - 0s 331ms/step
output when return_sequences is set to False [[-0.03455516]]


In [15]:
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation='softmax'))
#Determine the optimizer (optimizer), loss function (loss), and model evaluation method (metrics).
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.categorical_crossentropy,metrics=[tf.keras.metrics.categorical_accuracy])

In [16]:
train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 36))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100,
validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 0s 18ms/step - loss: 12.4370 - categorical_accuracy: 0.1150 - val_loss: 12.5144 - val_categorical_accuracy: 0.0800
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 12.4362 - categorical_accuracy: 0.1150 - val_loss: 12.5138 - val_categorical_accuracy: 0.0800
Epoch 3/10
10/10 [==============================] - 0s 4ms/step - loss: 12.4355 - categorical_accuracy: 0.1170 - val_loss: 12.5131 - val_categorical_accuracy: 0.0800
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 12.4348 - categorical_accuracy: 0.1160 - val_loss: 12.5126 - val_categorical_accuracy: 0.0800
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 12.4344 - categorical_accuracy: 0.1160 - val_loss: 12.5122 - val_categorical_accuracy: 0.0800
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 12.4344 - categorical_accuracy: 0.1160 - val_loss: 12.5126 - val_categorical_accuracy: 0.0800
Epo

In [17]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30, validation_data=val_dataset, validation_steps=3)

Epoch 1/10
30/30 [==============================] - 0s 4ms/step - loss: 12.4405 - categorical_accuracy: 0.1156 - val_loss: 12.6851 - val_categorical_accuracy: 0.0625
Epoch 2/10
30/30 [==============================] - 0s 1ms/step - loss: 12.4433 - categorical_accuracy: 0.1132 - val_loss: 12.6850 - val_categorical_accuracy: 0.0625
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - loss: 12.4177 - categorical_accuracy: 0.1132 - val_loss: 12.6842 - val_categorical_accuracy: 0.0625
Epoch 4/10
30/30 [==============================] - 0s 1ms/step - loss: 12.4234 - categorical_accuracy: 0.1197 - val_loss: 12.6821 - val_categorical_accuracy: 0.0625
Epoch 5/10
30/30 [==============================] - 0s 1ms/step - loss: 12.4640 - categorical_accuracy: 0.1197 - val_loss: 12.6795 - val_categorical_accuracy: 0.0625
Epoch 6/10
30/30 [==============================] - 0s 1ms/step - loss: 12.4099 - categorical_accuracy: 0.1154 - val_loss: 12.6767 - val_categorical_accuracy: 0.0625
Epoc

In [20]:
#Set hyperparameters.
Epochs = 10
#Define a function for dynamically setting the learning rate.
def lr_Scheduler(epoch):
    if epoch > 0.9 * Epochs:
        lr = 0.0001
    elif epoch > 0.5 * Epochs:
        lr = 0.001
    elif epoch > 0.25 * Epochs:
        lr = 0.01
    else:
        lr = 0.1
    print(lr)
    return lr

callbacks = [
    #Early stopping:
    tf.keras.callbacks.EarlyStopping(
        #Metric for determining whether the model performance has no further improvement
        monitor='val_loss',
        #Threshold for determining whether the model performance has no further improvement
        min_delta=1e-2,
        #Number of epochs in which the model performance has no further improvement
        patience=2),
    #Periodically save models.
    tf.keras.callbacks.ModelCheckpoint(
        #Model path
        filepath='testmodel_{epoch}.h5',
        #Whether to save the optimal model.
        save_best_only=True,
        #Monitored metric
        monitor='val_loss'),
    #Dynamically change the learning rate.
    tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),
    #Use TensorBoard.
    tf.keras.callbacks.TensorBoard(log_dir='./logs')
]
model.fit(train_x, train_y, batch_size=16, epochs=Epochs, callbacks=callbacks, validation_data=(val_x, val_y))

0.1
Epoch 1/10
63/63 [==============================] - 0s 7ms/step - loss: 12.6449 - categorical_accuracy: 0.1070 - val_loss: 12.2301 - val_categorical_accuracy: 0.1050 - lr: 0.1000
0.1
Epoch 2/10
63/63 [==============================] - 0s 3ms/step - loss: 12.7529 - categorical_accuracy: 0.0960 - val_loss: 12.3589 - val_categorical_accuracy: 0.0900 - lr: 0.1000
0.1
Epoch 3/10
63/63 [==============================] - 0s 3ms/step - loss: 12.6223 - categorical_accuracy: 0.1090 - val_loss: 12.8398 - val_categorical_accuracy: 0.1100 - lr: 0.1000


In [21]:
#Model evaluation
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)

32/32 [==============================] - 0s 869us/step - loss: 12.7567 - categorical_accuracy: 0.0990


[12.756681442260742, 0.0989999994635582]

In [22]:
#Model prediction
pre_x = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

32/32 [==============================] - 0s 869us/step
[[0.21213453 0.01688968 0.12129925 ... 0.03094566 0.23839283 0.04427894]
 [0.23553264 0.04286227 0.17534308 ... 0.03120978 0.1579748  0.05703686]
 [0.2877307  0.03458336 0.1494733  ... 0.05749008 0.08606611 0.14238487]
 ...
 [0.14241174 0.03709368 0.11599211 ... 0.04243736 0.2247436  0.1043625 ]
 [0.15546234 0.03359032 0.10874239 ... 0.0485792  0.24761067 0.05105059]
 [0.16692035 0.09446618 0.10455814 ... 0.0266568  0.22664024 0.03595393]]


In [25]:
import os
# create the file
if not os.path.exists('./model/'):
    os.mkdir('./model/')
#Save models.
model.save('./model/the_save_model.h5')
#Import models.
new_model = tf.keras.models.load_model('./model/the_save_model.h5')
new_prediction = new_model.predict(test_x)
#np.testing.assert_allclose: determines whether the similarity between two objects exceeds the specified tolerance. If yes, the system displays an exception.
#atol: specified tolerance
np.testing.assert_allclose(result, new_prediction, atol=1e-6)

32/32 [==============================] - 0s 836us/step


In [26]:
model.save_weights('./model/model_weights')
model.save_weights('./model/model_weights.h5')
#Load the weights.
model.load_weights('./model/model_weights')
model.load_weights('./model/model_weights.h5')